version: 2

project_name: lazygh

builds:
  - id: lazygh
    main: ./cmd/lazygh
    binary: lazygh
    env:
      - CGO_ENABLED=1
      - CC_darwin_amd64=o64-clang
      - CXX_darwin_amd64=o64-clang++
      - CC_darwin_arm64=oa64-clang
      - CXX_darwin_arm64=oa64-clang++
      - CC_linux_amd64=x86_64-linux-gnu-gcc
      - CXX_linux_amd64=x86_64-linux-gnu-g++
      - CC_linux_arm64=aarch64-linux-gnu-gcc
      - CXX_linux_arm64=aarch64-linux-gnu-g++
      - CC_windows_amd64=x86_64-w64-mingw32-gcc
      - CXX_windows_amd64=x86_64-w64-mingw32-g++
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: lazygh
    ids:
      - lazygh
    wrap_in_directory: true
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
