name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: codeberg-medium
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.25.9
    steps:
      - name: Checkout repository
        run: |
          git config --global --add safe.directory "$PWD"
          git init .
          git remote add origin "${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}.git"
          git fetch --force --tags origin
          git checkout --force "${FORGEJO_SHA}"

      - name: Run test suite
        run: go test ./...

      - name: Build local binary
        run: mkdir -p ./bin && go build -o ./bin/lazygh ./cmd/lazygh

      - name: Publish release
        env:
          GORELEASER_FORCE_TOKEN: gitea
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --clean --config .goreleaser.yaml
