package theme

const (
	ActiveBorderHex                      = "#000000"
	InactiveBorderHex                    = "#CCCCCC"
	ActiveTextHex                        = "#000000"
	InactiveTextHex                      = "#000000"
	InactiveTitleHex                     = "#CCCCCC"
	SelectedLineBackgroundHex            = "#E6E6E6"
	SearchHighlightHex                   = "#F9EAB3"
	MarkdownHeadingHex                   = "#1D4ED8"
	MarkdownLinkHex                      = "#0F766E"
	MarkdownCodeHex                      = "#B45309"
	CommentAuthorBadgeForegroundHex      = "#0969DA"
	CommentAuthorBadgeBackgroundHex      = "#DDF4FF"
	PullRequestStatusOpenForegroundHex   = "#1A7F37"
	PullRequestStatusOpenBackgroundHex   = "#DFF3E4"
	PullRequestStatusDraftForegroundHex  = "#656D76"
	PullRequestStatusDraftBackgroundHex  = "#E6E6E6"
	PullRequestStatusClosedForegroundHex = "#CF222E"
	PullRequestStatusClosedBackgroundHex = "#FFE2E5"
	PullRequestStatusMergedForegroundHex = "#8250DF"
	PullRequestStatusMergedBackgroundHex = "#F5EDFF"
	DiffAdditionForegroundHex            = "#1A7F37"
	DiffAdditionBackgroundHex            = "#DFF3E4"
	DiffDeletionForegroundHex            = "#CF222E"
	DiffDeletionBackgroundHex            = "#FFE2E5"
	DiffLineNumberHex                    = "#656D76"
	DiffHunkHeaderHex                    = "#656D76"
)
