[keymaps.global]
quit = "ctrl+c"
next_side_view = ["tab", "l"]
previous_side_view = ["shift+tab", "h"]
toggle_help = "?"
open_search = "/"
move_selection_down = ["j", "down"]
move_selection_up = ["k", "up"]
page_down = "ctrl+d"
page_up = "ctrl+u"
full_page_down = ["ctrl+f", "pagedown"]
full_page_up = ["ctrl+b", "pageup"]
grow_focused_pane = "+"
shrink_focused_pane = "-"
open_actions_popup = "a"
refresh = "alt+r"
previous_tab = "["
next_tab = "]"
close = ["esc", "q"]

[keymaps.selection]
move_selection_to_top = "gg"
move_selection_to_bottom = "G"
place_selection_at_viewport_top = "zt"
recenter_selection = "zz"
place_selection_at_viewport_bottom = "zb"

[keymaps.cursor]
move_cursor_left = ["h", "left"]
move_cursor_right = ["l", "right"]
move_cursor_to_row_start = "0"
move_cursor_to_row_end = "$"
move_cursor_to_top = "gg"
open_link_under_cursor = "gx"
toggle_word_wrap = "ctrl+w"
search_word_under_cursor_forward = "*"
search_word_under_cursor_backward = "#"
move_cursor_to_bottom = "G"
move_cursor_to_next_word = "w"
move_cursor_to_word_end = "e"
move_cursor_to_previous_word = "b"
move_cursor_to_next_big_word = "W"
move_cursor_to_big_word_end = "E"
move_cursor_to_previous_big_word = "B"
find_character_forward = "f"
find_character_backward = "F"
till_character_forward = "t"
till_character_backward = "T"
repeat_character_motion_forward = ";"
repeat_character_motion_backward = ","
start_yank = "y"
move_cursor_to_other_end = "o"
enter_visual_mode = "v"
enter_line_visual_mode = "V"
recenter_cursor = "zz"
place_cursor_at_viewport_top = "zt"
place_cursor_at_viewport_bottom = "zb"

[keymaps.main]
move_detail_view_down = "J"
move_detail_view_up = "K"

[keymaps.side]
open_detail = "enter"
exit_review_mode = ["esc", "q"]

[keymaps.folds]
toggle_fold = "za"
close_all_folds = "zM"
open_all_folds = "zR"

[keymaps.review]
previous_file = "[["
next_file = "]]"
previous_comment = "[c"
next_comment = "]c"

[keymaps.pull_requests]
copy_pull_request_url = "alt+y"
open_pull_request_in_browser = "alt+b"
comment_on_pull_request = "c"
custom_search = ":"
open_pull_request_by_url = "ctrl+v"
reply_to_inline_comment = "r"
toggle_inline_comment_resolution = "ctrl+r"

[keymaps.notifications]
mark_notification_read = "r"
mark_notification_done = "d"

[keymaps.search]
submit = ["enter", "ctrl+j", "ctrl+s"]
cancel = ["esc"]
next_search_match = "n"
previous_search_match = "N"

[keymaps.actions_popup]
execute_selected_action = "enter"
submit_selected_picker = "alt+enter"

[keymaps.modal_editor]
submit = ["alt+enter", "ctrl+s"]
submit_line = ["enter", "ctrl+s"]
open_external_editor = "ctrl+g"
cancel = "esc"

[keymaps.pull_request_build_info]
copy_content = "alt+y"
